version: "3.8"
services:

    # PHP service
    app:
        build: .
        image: repox/laravel-dev-php:8.0
        container_name: php-app
        working_dir: /var/www/
        volumes:
            - ./../:/var/www
        networks:
            - app-network

    # MySQL database service
    db:
        image: mysql:5.7
        container_name: mysql-db
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: geopagosdb
            MYSQL_USER: geopagosusr
            MYSQL_PASSWORD: geopagospwd
        volumes:
            - ./mysql/my.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
        networks:
            - app-network

    # Nginx service
    nginx:
        image: nginx:alpine
        container_name: php-nginx
        ports:
            - 8000:80
        volumes:
            - ./../:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network

networks:
    app-network:
        driver: bridge